name: Release on main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: windows
            arch: amd64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          BIN_NAME="simplelogin"
          EXT=""
          if [ "${{ matrix.os }}" = "windows" ]; then EXT=".exe"; fi
          mkdir -p dist/${{ matrix.os }}-${{ matrix.arch }}
          go build -trimpath -ldflags "-s -w" -o dist/${{ matrix.os }}-${{ matrix.arch }}/${BIN_NAME}${EXT} ./cmd/simplelogin

      - name: Package
        run: |
          set -euo pipefail
          NAME="simplelogin-${{ matrix.os }}-${{ matrix.arch }}"
          cd dist/${{ matrix.os }}-${{ matrix.arch }}
          if [ "${{ matrix.os }}" = "windows" ]; then
            zip -9 ../${NAME}.zip simplelogin.exe
          else
            tar -czf ../${NAME}.tar.gz simplelogin
          fi
          cd -

      - name: Generate checksums
        run: |
          cd dist
          for f in simplelogin-*.tar.gz simplelogin-*.zip 2>/dev/null; do
            [ -f "$f" ] || continue
            sha256sum "$f" >> SHA256SUMS-${{ matrix.os }}-${{ matrix.arch }}.txt
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            dist/*.tar.gz
            dist/*.zip
            dist/SHA256SUMS-${{ matrix.os }}-${{ matrix.arch }}.txt
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate tag and name
        id: meta
        run: |
          short_sha="${GITHUB_SHA::7}"
          stamp=$(date -u +"%Y%m%d-%H%M%S")
          echo "tag=v${stamp}-${short_sha}" >> "$GITHUB_OUTPUT"
          echo "name=SimpleLogin CLI ${stamp} (${short_sha})" >> "$GITHUB_OUTPUT"

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/**/**/*.tar.gz
            dist/**/**/*.zip
            dist/**/**/SHA256SUMS-*.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
